 const input1 = document.querySelector('.in1')
 const input2= document.querySelector('.in2')
 const input3 = document.querySelector('.in3')
 const chebox1= document.querySelector('.checkboxs1')
 const chebox2= document.querySelector('.checkboxs2')
 const chebox3= document.querySelector('.checkboxs3')
 const inputText= document.querySelector('.in')
 

chebox1. addEventListener('click',()=>{

chebox1.classList.toggle('complet')
input1.classList.toggle('complet1')
 })
chebox2. addEventListener('click',()=>{

chebox2.classList.toggle('complet')
input2.classList.toggle('complet1')
 })
chebox3. addEventListener('click',()=>{

chebox3.classList.toggle('complet')
input3.classList.toggle('complet1')
 })
 

    
